# Generated by Django 4.1.6 on 2023-02-02 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eda',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EdaItems',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.IntegerField()),
                ('text', models.TextField()),
                ('image', models.BinaryField(null=True)),
                ('eda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eda.eda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EdaIngredients',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.CharField(max_length=30)),
                ('eda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='eda.eda')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eda.ingredients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('eda', models.ManyToManyField(to='eda.eda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
